device: cuda
seed: 0
ts_length: 5
batch_size: 16
num_workers: 0


Evaluation:
  test_ratio: 0.2
  n_eval: 5
  batch_size: 2
  metrics_enabled: [
#    'discriminative_score',
#    'predictive_score',
     'hist_loss',
     'acf_loss',
     'cov_loss',
     'cross_corr',
     'var',
     'es'
    ]

  TestMetrics:
      discriminative_score:
        hidden_size: 32
        epochs : 10
        num_layers: 2
        batch_size: 128

      predictive_score:
        hidden_size: 32
        epochs : 10
        num_layers: 2
        batch_size: 128

      hist_loss:
        keep_init: True
        n_bins: 30

      cross_corr: None

      acf_loss:
        stationary: False # False, depend on dataset
        keep_init: False

      cov_loss: None

      var:
        alpha: 0.05

      es:
        alpha: 0.05